openapi: 3.0.0
info:
  title: BlogPosts
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/user.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ''
components:
  schemas: {}
  securitySchemes: {}
